### ISSUE TITLE
Removed from npm?

### ISSUE THREAD

**Issue by jfexyz** [kswedberg/ump#1]
Did this get removed?

**Comment by kswedberg** [comment]
I don't think I ever added it. I was going to wait until I had a decent set of tests for it, but maybe I'll just publish with a 0.x.x version number.

**Comment by kswedberg** [comment]
Okay, here you go: https://www.npmjs.com/package/ump

**Comment by jfexyz** [comment]
I must have discovered it via Github and just assumed it was on npm. :) thanks!

**Comment by kswedberg** [comment]
No problem. Enjoy!
